# -*- coding: utf-8 -*-
"""subject_wise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiLlORonscw81loQe0Mcfq8uUy-32Ran
"""

import os
import numpy as np
from PIL import Image
from sklearn.model_selection import KFold
from imblearn.over_sampling import SMOTE

def collect_breakhis_paths(root_dir, magnification="40X"):
    image_paths = []
    labels = []
    patient_ids = []

    benign_classes    = ["adenosis", "fibroadenoma", "phyllodes_tumor", "tubular_adenoma"]
    malignant_classes = ["ductal_carcinoma", "lobular_carcinoma", "mucinous_carcinoma", "papillary_carcinoma"]

    class_info = [(benign_classes, 0, "benign"), (malignant_classes, 1, "malignant")]

    for cls_list, label, category in class_info:
        for cls in cls_list:
            cls_path = os.path.join(root_dir, "histology_slides", "breast", category, "SOB", cls)
            if not os.path.exists(cls_path):
                continue
            for patient_folder in os.listdir(cls_path):
                patient_path = os.path.join(cls_path, patient_folder, magnification)
                if not os.path.exists(patient_path):
                    continue
                for fname in os.listdir(patient_path):
                    if fname.endswith(".png"):
                        image_paths.append(os.path.join(patient_path, fname))
                        labels.append(label)
                        patient_ids.append(patient_folder)

    return np.array(image_paths), np.array(labels), np.array(patient_ids)

def load_images(image_paths, labels, img_size=(128, 128)):
    images = []
    for path in image_paths:
        img = Image.open(path)
        img = img.resize(img_size)
        images.append(np.array(img))
    return np.array(images), np.array(labels)

def normalize(images):
    min_val = images.min()
    max_val = images.max()
    return (images - min_val) / (max_val - min_val + 1e-8)

def subject_wise_kfold(patient_ids, n_splits=5):
    unique_patients = np.unique(patient_ids)
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

    folds = []
    for train_pat_idx, test_pat_idx in kf.split(unique_patients):
        train_patients = unique_patients[train_pat_idx]
        test_patients  = unique_patients[test_pat_idx]

        train_idx = np.where(np.isin(patient_ids, train_patients))[0]
        test_idx  = np.where(np.isin(patient_ids, test_patients))[0]

        folds.append((train_idx, test_idx))

    return folds

def split_train_val(train_idx, patient_ids, val_size=0.1):
    train_patients = np.unique(patient_ids[train_idx])

    n_val = max(1, int(len(train_patients) * val_size))

    np.random.seed(42)
    val_patients = np.random.choice(train_patients, size=n_val, replace=False)
    tr_patients  = np.setdiff1d(train_patients, val_patients)

    tr_idx  = np.where(np.isin(patient_ids, tr_patients))[0]
    val_idx = np.where(np.isin(patient_ids, val_patients))[0]

    return tr_idx, val_idx

def apply_smote(X_train, y_train):
    original_shape = X_train.shape[1:]
    X_flat = X_train.reshape(len(X_train), -1)

    smote = SMOTE(random_state=42)
    X_resampled, y_resampled = smote.fit_resample(X_flat, y_train)

    X_resampled = X_resampled.reshape(-1, *original_shape)
    return X_resampled, y_resampled

def prepare_fold_data(images, labels, patient_ids, train_idx, test_idx):
    X_test  = normalize(images[test_idx])
    y_test  = labels[test_idx]

    tr_idx, val_idx = split_train_val(train_idx, patient_ids)

    X_val   = normalize(images[val_idx])
    y_val   = labels[val_idx]
    X_train = normalize(images[tr_idx])
    y_train = labels[tr_idx]

    X_train, y_train = apply_smote(X_train, y_train)

    return X_train, y_train, X_val, y_val, X_test, y_test