# -*- coding: utf-8 -*-
"""01_Final_Class_Based.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6n-VggSlu43bSn7-LYuBqapBGcQKDng
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Model

class PositionEmbedding(layers.Layer):
    def __init__(self, sequence_length: int, initializer="glorot_uniform", **kwargs):
        super().__init__(**kwargs)
        self.sequence_length = int(sequence_length)
        self.initializer = keras.initializers.get(initializer)

    def build(self, input_shape):
        embed_dim = int(input_shape[-1])
        self.pos_emb = self.add_weight(
            name="pos_emb",
            shape=(self.sequence_length, embed_dim),
            initializer=self.initializer,
            trainable=True,
        )
        super().build(input_shape)

    def call(self, token_embeddings):
        return token_embeddings + tf.expand_dims(self.pos_emb, axis=0)

class SequencePooling(layers.Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.attn_score = layers.Dense(1)

    def call(self, token_embeddings):
        attn_weights = tf.nn.softmax(self.attn_score(token_embeddings), axis=1)
        attn_weights = tf.transpose(attn_weights, perm=(0, 2, 1))
        pooled = tf.matmul(attn_weights, token_embeddings)
        return tf.squeeze(pooled, axis=1)

class PatchStem(layers.Layer):
    def __init__(self, embed_dim: int, patch_size: int, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = int(embed_dim)
        self.patch_size = int(patch_size)

        self.proj = layers.Conv2D(
            filters=self.embed_dim,
            kernel_size=self.patch_size,
            strides=self.patch_size,
            padding="valid",
        )
        self.act = layers.Activation("gelu")
        self.bn = layers.BatchNormalization()

    def call(self, images, training=False):
        patch_features = self.proj(images)
        patch_features = self.act(patch_features)
        patch_features = self.bn(patch_features, training=training)
        return patch_features

class ConvMixBlock(layers.Layer):
    def __init__(self, embed_dim: int, kernel_size: int, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = int(embed_dim)
        self.kernel_size = int(kernel_size)

        self.dw_conv = layers.DepthwiseConv2D(self.kernel_size, padding="same")
        self.dw_act = layers.Activation("gelu")
        self.dw_bn = layers.BatchNormalization()
        self.residual_add = layers.Add()

        self.pw_conv = layers.Conv2D(self.embed_dim, kernel_size=1, padding="same")
        self.pw_act = layers.Activation("gelu")
        self.pw_bn = layers.BatchNormalization()

    def call(self, spatial_features, training=False):
        residual = spatial_features

        spatial_features = self.dw_conv(spatial_features)
        spatial_features = self.dw_act(spatial_features)
        spatial_features = self.dw_bn(spatial_features, training=training)
        spatial_features = self.residual_add([spatial_features, residual])

        spatial_features = self.pw_conv(spatial_features)
        spatial_features = self.pw_act(spatial_features)
        spatial_features = self.pw_bn(spatial_features, training=training)

        return spatial_features

class TransformerEncoderBlock(layers.Layer):
    def __init__(self, embed_dim: int, num_heads: int, key_dim: int, dropout: float, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = int(embed_dim)
        self.num_heads = int(num_heads)
        self.key_dim = int(key_dim)
        self.dropout = float(dropout)

        self.pre_attn_norm = layers.LayerNormalization(epsilon=1e-6)
        self.self_attn = layers.MultiHeadAttention(
            num_heads=self.num_heads,
            key_dim=self.key_dim,
            dropout=self.dropout,
        )
        self.attn_drop = layers.Dropout(self.dropout)
        self.attn_add = layers.Add()

        self.pre_mlp_norm = layers.LayerNormalization(epsilon=1e-6)
        self.mlp_fc1 = layers.Dense(self.embed_dim * 4, activation="gelu")
        self.mlp_drop1 = layers.Dropout(self.dropout)
        self.mlp_fc2 = layers.Dense(self.embed_dim)
        self.mlp_drop2 = layers.Dropout(self.dropout)
        self.mlp_add = layers.Add()

    def call(self, token_embeddings, training=False):
        attn_inp = self.pre_attn_norm(token_embeddings)
        attn_out = self.self_attn(attn_inp, attn_inp, training=training)
        attn_out = self.attn_drop(attn_out, training=training)
        token_embeddings = self.attn_add([token_embeddings, attn_out])

        mlp_inp = self.pre_mlp_norm(token_embeddings)
        mlp_out = self.mlp_fc1(mlp_inp)
        mlp_out = self.mlp_drop1(mlp_out, training=training)
        mlp_out = self.mlp_fc2(mlp_out)
        mlp_out = self.mlp_drop2(mlp_out, training=training)
        token_embeddings = self.mlp_add([token_embeddings, mlp_out])

        return token_embeddings

class MixFormerBC(Model):
    def __init__(
        self,
        input_shape=(128, 128, 3),
        num_classes=2,
        patch_size=4,
        embed_dim=256,
        conv_depth=16,
        kernel_size=3,
        num_heads=2,
        transformer_depth=2,
        dropout=0.10,
        **kwargs,
    ):
        super().__init__(**kwargs)

        self.input_shape_cfg = tuple(input_shape)
        self.num_classes = int(num_classes)
        self.patch_size = int(patch_size)
        self.embed_dim = int(embed_dim)
        self.conv_depth = int(conv_depth)
        self.kernel_size = int(kernel_size)
        self.num_heads = int(num_heads)
        self.transformer_depth = int(transformer_depth)
        self.dropout = float(dropout)

        height, width, _ = self.input_shape_cfg
        self.seq_len = (height // self.patch_size) * (width // self.patch_size)
        self.key_dim = self.embed_dim // self.num_heads

        self.patch_stem = PatchStem(embed_dim=self.embed_dim, patch_size=self.patch_size)

        self.convmixer_stack = [
            ConvMixBlock(embed_dim=self.embed_dim, kernel_size=self.kernel_size)
            for _ in range(self.conv_depth)
        ]

        self.global_avg_pool = layers.GlobalAveragePooling2D()

        self.position_embedding = PositionEmbedding(self.seq_len)
        self.sequence_pool = SequencePooling()

        self.transformer_encoder = [
            TransformerEncoderBlock(
                embed_dim=self.embed_dim,
                num_heads=self.num_heads,
                key_dim=self.key_dim,
                dropout=self.dropout,
            )
            for _ in range(self.transformer_depth)
        ]

        self.feature_fusion = layers.Concatenate()
        self.classifier_head = layers.Dense(self.num_classes, activation="softmax")

    def call(self, images, training=False):
        spatial_features = self.patch_stem(images, training=training)

        for conv_block in self.convmixer_stack:
            spatial_features = conv_block(spatial_features, training=training)

        gap_features = self.global_avg_pool(spatial_features)

        token_embeddings = tf.reshape(spatial_features, shape=(-1, self.seq_len, self.embed_dim))
        token_embeddings = self.position_embedding(token_embeddings)

        for encoder_block in self.transformer_encoder:
            token_embeddings = encoder_block(token_embeddings, training=training)

        token_pooled = self.sequence_pool(token_embeddings)

        fused_features = self.feature_fusion([gap_features, token_pooled])
        class_probs = self.classifier_head(fused_features)

        return class_probs