# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiLlORonscw81loQe0Mcfq8uUy-32Ran
"""

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    cohen_kappa_score,
    roc_auc_score,
    confusion_matrix,
)

def compute_accuracy(y_true, y_pred):
    return accuracy_score(y_true, y_pred) * 100.0

def compute_precision(y_true, y_pred):
    return precision_score(y_true, y_pred, zero_division=0) * 100.0

def compute_recall(y_true, y_pred):
    return recall_score(y_true, y_pred, zero_division=0) * 100.0

def compute_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, zero_division=0) * 100.0

def compute_specificity(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    if (tn + fp) == 0:
        return 0.0
    return (tn / (tn + fp)) * 100.0

def compute_cohen_kappa(y_true, y_pred):
    return cohen_kappa_score(y_true, y_pred) * 100.0

def compute_auc_roc(y_true, y_prob):
    return roc_auc_score(y_true, y_prob) * 100.0

def compute_all_metrics(y_true, y_pred, y_prob):
    return {
        "accuracy":    compute_accuracy(y_true, y_pred),
        "precision":   compute_precision(y_true, y_pred),
        "recall":      compute_recall(y_true, y_pred),
        "f1_score":    compute_f1(y_true, y_pred),
        "specificity": compute_specificity(y_true, y_pred),
        "cohen_kappa": compute_cohen_kappa(y_true, y_pred),
        "auc_roc":     compute_auc_roc(y_true, y_prob),
    }

def aggregate_fold_metrics(fold_metrics):
    keys = fold_metrics[0].keys()
    aggregated = {}
    for key in keys:
        values = np.array([fm[key] for fm in fold_metrics])
        aggregated[key] = {
            "mean": float(np.mean(values)),
            "std":  float(np.std(values)),
        }
    return aggregated